dist: trusty
sudo: false

language: scala

jdk:
  - openjdk11

scala:
  - 2.12.8

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: sbt ++$TRAVIS_SCALA_VERSION coverageReport coverageAggregate coveralls

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "MHaxkz95FNDxMv62R1ItC+XFhidyom5AZGD8XgadRkD88FTQvS9k4Qc+bPjZl70pQ9h+x/S5LTeOXmptYFkWJuNC9Guf2CeLBwe91d6I2X4X4Sq7vKqOHSTJQg2U0Ra3sC0WbFeKsHv2137dS6M5SAwvC/16X9YbtmUuvn7BWmc30WKP4+bvOVMbQStQramKgCoD0UvRQkdx0TuuEXnS+X/mYcdqmIVhVh+CzW6xRuvxlMPf49DsistQeTGfGVGVzsWj8tjaNVcR3+9OlETobMAD6wFzfxlvlPR9p/2mTCTy2zV9Ehz8PEMAEijcWbx/BZnuVUScuI/Djf9ax2Gy8cb+7YG/AsGK4oKYeOi1PHPDkXTdEBS1KBQuJ/gQsjxqfddCYuvELpDgXYz4fahcZ+swXdzBR7FcEfPzufZj7dVc6Jex4jh0gOgbjzWtxy9mCy3jg6g1AIlcfOsxEOA5y0Qu5X4UPzpGv4UxEQ4Keq4MZgFvZdYYubFF3iEs63FLuC+dKhjsH82WAN72jd64WGQjst4ObfT/L2JGffrb029GIX3+jYSCEL6H454CmQao77Nm3OiRYFzPZ8jTNDSsqUSRLPAzMWT2CleLNUAo+VXVw7+oBIlOEF5bgr1roQzm14PfKN+g3oEQ+FaH6OWf5gBZ+XQsjueFteHQoZvHvro="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
